name: streaming-osm
version: '1.0.0'
synopsis: A hand-written streaming byte parser for OpenStreetMap Protobuf data.
description: A hand-written streaming byte parser for OpenStreetMap Protobuf data.
category: Streaming
author: Colin Woodbury
maintainer: colingw@gmail.com
copyright: Copyright (c) 2017 Azavea
license: BSD3

extra-source-files:
  - ChangeLog.md
  - test/*.osm.pbf

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -O2

dependencies:
  - base >=4.8 && <4.11
  - attoparsec >=0.13 && <0.14
  - bytestring
  - streaming >=0.1 && <0.2
  - vector >= 0.11 && < 0.13
  - zlib >=0.6 && <0.7

library:
  source-dirs: src
  dependencies:
    - containers
    - streaming-bytestring >=0.1 && <0.2
    - streaming-utils >= 0.1 && < 0.2
    - text
    - transformers

tests:
  streaming-osm-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -threaded
    dependencies:
      - streaming-osm
      - tasty >=0.11 && <0.12
      - tasty-hunit >=0.9 && <0.10

benchmarks:
  streaming-osm-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
    dependencies:
      - criterion >= 1.1 && < 1.3
      - streaming-osm

# executables:
#   profiling:
#     source-dirs: profile
#     main: Profile.hs
#     ghc-options:
#       - -threaded
#     dependencies:
#       - streaming-osm
